// Code generated by protoc-gen-go. DO NOT EDIT.
// source: chatroom.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type User struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ca54b9e3ca377ae, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Message struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Content              string   `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Timestamp            string   `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ca54b9e3ca377ae, []int{1}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Message) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *Message) GetTimestamp() string {
	if m != nil {
		return m.Timestamp
	}
	return ""
}

type Connect struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Active               bool     `protobuf:"varint,2,opt,name=active,proto3" json:"active,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Connect) Reset()         { *m = Connect{} }
func (m *Connect) String() string { return proto.CompactTextString(m) }
func (*Connect) ProtoMessage()    {}
func (*Connect) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ca54b9e3ca377ae, []int{2}
}

func (m *Connect) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Connect.Unmarshal(m, b)
}
func (m *Connect) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Connect.Marshal(b, m, deterministic)
}
func (m *Connect) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Connect.Merge(m, src)
}
func (m *Connect) XXX_Size() int {
	return xxx_messageInfo_Connect.Size(m)
}
func (m *Connect) XXX_DiscardUnknown() {
	xxx_messageInfo_Connect.DiscardUnknown(m)
}

var xxx_messageInfo_Connect proto.InternalMessageInfo

func (m *Connect) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *Connect) GetActive() bool {
	if m != nil {
		return m.Active
	}
	return false
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ca54b9e3ca377ae, []int{3}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

func init() {
	proto.RegisterType((*User)(nil), "proto.User")
	proto.RegisterType((*Message)(nil), "proto.Message")
	proto.RegisterType((*Connect)(nil), "proto.Connect")
	proto.RegisterType((*Empty)(nil), "proto.Empty")
}

func init() {
	proto.RegisterFile("chatroom.proto", fileDescriptor_9ca54b9e3ca377ae)
}

var fileDescriptor_9ca54b9e3ca377ae = []byte{
	// 239 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x8f, 0xcf, 0x4a, 0x03, 0x31,
	0x10, 0xc6, 0xbb, 0xeb, 0xb6, 0xdb, 0x4e, 0xcb, 0x22, 0x73, 0x90, 0xa5, 0x08, 0x4a, 0x4e, 0xe2,
	0xa1, 0xc8, 0xfa, 0x06, 0x5d, 0x3c, 0x7a, 0x70, 0xc5, 0x07, 0x18, 0xb3, 0x83, 0xe6, 0x90, 0x64,
	0x49, 0x46, 0xc1, 0xb7, 0x17, 0xd3, 0x54, 0x91, 0x9e, 0x92, 0xdf, 0xfc, 0xfb, 0xbe, 0x0f, 0x1a,
	0xfd, 0x4e, 0x12, 0xbc, 0xb7, 0xbb, 0x29, 0x78, 0xf1, 0x38, 0x4f, 0x8f, 0xba, 0x85, 0xea, 0x25,
	0x72, 0xc0, 0x06, 0x4a, 0x33, 0xb6, 0xc5, 0x75, 0x71, 0xb3, 0x1a, 0x4a, 0x33, 0x22, 0x42, 0xe5,
	0xc8, 0x72, 0x5b, 0xa6, 0x4a, 0xfa, 0xab, 0x27, 0xa8, 0x1f, 0x39, 0x46, 0x7a, 0xe3, 0x93, 0xf1,
	0x16, 0x6a, 0xed, 0x9d, 0xb0, 0x93, 0xbc, 0x71, 0x44, 0xbc, 0x84, 0x95, 0x18, 0xcb, 0x51, 0xc8,
	0x4e, 0xed, 0x59, 0xea, 0xfd, 0x15, 0xd4, 0x1e, 0xea, 0xde, 0x3b, 0xc7, 0x5a, 0xf0, 0x0a, 0xaa,
	0x8f, 0xc8, 0x21, 0x1d, 0x5d, 0x77, 0xeb, 0x83, 0xcd, 0xdd, 0x8f, 0xb9, 0x21, 0x35, 0xf0, 0x02,
	0x16, 0xa4, 0xc5, 0x7c, 0x1e, 0x4c, 0x2d, 0x87, 0x4c, 0xaa, 0x86, 0xf9, 0x83, 0x9d, 0xe4, 0xab,
	0x0b, 0xb0, 0xec, 0x73, 0x48, 0xec, 0x60, 0xd3, 0x07, 0x26, 0xe1, 0x67, 0x09, 0x4c, 0x16, 0x9b,
	0x7c, 0x2f, 0xab, 0x6d, 0x8f, 0x9c, 0x03, 0xa9, 0xd9, 0x5d, 0x81, 0x1d, 0x9c, 0xef, 0x83, 0xa7,
	0x51, 0x53, 0x94, 0xdf, 0xa0, 0xff, 0xe7, 0xb6, 0x9b, 0xcc, 0x49, 0x51, 0xcd, 0x5e, 0x17, 0x09,
	0xef, 0xbf, 0x03, 0x00, 0x00, 0xff, 0xff, 0x51, 0x4c, 0xed, 0x7b, 0x5f, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ChatroomClient is the client API for Chatroom service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ChatroomClient interface {
	CreateStream(ctx context.Context, in *Connect, opts ...grpc.CallOption) (Chatroom_CreateStreamClient, error)
	BroadcastMessage(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Empty, error)
}

type chatroomClient struct {
	cc grpc.ClientConnInterface
}

func NewChatroomClient(cc grpc.ClientConnInterface) ChatroomClient {
	return &chatroomClient{cc}
}

func (c *chatroomClient) CreateStream(ctx context.Context, in *Connect, opts ...grpc.CallOption) (Chatroom_CreateStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Chatroom_serviceDesc.Streams[0], "/proto.Chatroom/CreateStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &chatroomCreateStreamClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Chatroom_CreateStreamClient interface {
	Recv() (*Message, error)
	grpc.ClientStream
}

type chatroomCreateStreamClient struct {
	grpc.ClientStream
}

func (x *chatroomCreateStreamClient) Recv() (*Message, error) {
	m := new(Message)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *chatroomClient) BroadcastMessage(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/proto.Chatroom/BroadcastMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChatroomServer is the server API for Chatroom service.
type ChatroomServer interface {
	CreateStream(*Connect, Chatroom_CreateStreamServer) error
	BroadcastMessage(context.Context, *Message) (*Empty, error)
}

// UnimplementedChatroomServer can be embedded to have forward compatible implementations.
type UnimplementedChatroomServer struct {
}

func (*UnimplementedChatroomServer) CreateStream(req *Connect, srv Chatroom_CreateStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method CreateStream not implemented")
}
func (*UnimplementedChatroomServer) BroadcastMessage(ctx context.Context, req *Message) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BroadcastMessage not implemented")
}

func RegisterChatroomServer(s *grpc.Server, srv ChatroomServer) {
	s.RegisterService(&_Chatroom_serviceDesc, srv)
}

func _Chatroom_CreateStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Connect)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ChatroomServer).CreateStream(m, &chatroomCreateStreamServer{stream})
}

type Chatroom_CreateStreamServer interface {
	Send(*Message) error
	grpc.ServerStream
}

type chatroomCreateStreamServer struct {
	grpc.ServerStream
}

func (x *chatroomCreateStreamServer) Send(m *Message) error {
	return x.ServerStream.SendMsg(m)
}

func _Chatroom_BroadcastMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Message)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatroomServer).BroadcastMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Chatroom/BroadcastMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatroomServer).BroadcastMessage(ctx, req.(*Message))
	}
	return interceptor(ctx, in, info, handler)
}

var _Chatroom_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Chatroom",
	HandlerType: (*ChatroomServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "BroadcastMessage",
			Handler:    _Chatroom_BroadcastMessage_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "CreateStream",
			Handler:       _Chatroom_CreateStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "chatroom.proto",
}
